name: 'Build and push docker image to ECR'
description: 'Greet someone'
inputs:
  ecr_repository:
    description: 'ECR Repository'
    required: true
  image_tag:
    description: 'Docker image tag'
    required: true
    default: 'latest'
  path:
    description: 'Path to root folder with image'
    required: false
    default: .
  github_token:
    description: 'Github token'
    required: false

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        submodules: true

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      shell: bash
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr_repository }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ${{ inputs.path }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
