name: 'Build and push docker image to ECR'
description: 'Greet someone'
inputs:
  ecr_registry:
    description: 'ECR registry'
    required: true
  ecr_repository:
    description: 'ECR Repository'
    required: true
  image_tag:
    description: 'Docker image tag'
    required: true
    default: 'latest'
  aws_access_key_id:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws_secret_access_key:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  path:
    description: 'Path to root folder with image'
    required: false
    default: .
  github_token:
    description: 'Github token'
    required: false

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        submodules: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      shell: bash
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr_repository }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ${{ inputs.path }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
